# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_decimal', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('some_float', models.FloatField(null=True)),
                ('some_duration', models.DurationField(null=True)),
                ('some_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_int', models.IntegerField(blank=True, null=True)),
                ('some_string', models.CharField(max_length=254)),
                ('some_text', models.TextField(blank=True)),
                ('some_boolean', models.BooleanField()),
                ('some_nullable_boolean', models.NullBooleanField()),
                ('some_date', models.DateField(null=True)),
                ('some_datetime', models.DateTimeField(null=True)),
                ('some_time', models.TimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='some_foo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Foo'),
        ),
    ]
